apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: b4rucxs2n-python 
  janus-idp.io/tekton: b4rucxs2n-python
  backstage.io/kubernetes-id: b4rucxs2n-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: b4rucxs2n-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml